vars: {
    d2-config: {
      layout-engine: tala
    }
  }
  direction: down

  scripts.nf {
    shape: page
    style.multiple: true
  }
  parameters.yml {
    shape: page
    style.multiple: true
  }
  scripts.nf -> modules: software/tools
  parameters.yml -> modules: inputs/outputs
  modules {
    shape: page
    style.multiple: true
  }
  properties.config {
    shape: page
    style.multiple: true
  }
  metadata.yml {
    shape: page
    style.multiple: true
  }

  properties.config -> sub workflows: configuration
  metadata.yml -> sub workflows: description
  sub workflows {
    shape: page
    style.multiple: true
  }
  modules -> sub workflows: import
  sub workflows -> Main workflow: pipeline
  Sample Sheet {
    shape: sql_table
    specimen_id: specimen id
    patient_id: patient id
    tissue: tumor source site
    purity: tumor cell percentages in tissue
    read1/2: paired end raw reads
  }

    Main Workflow {
        Trim sequence adapters  {
            a: |
                - remove sequencing adapters 
                - generate prior/post QC reports
                |
        }
        Align reads to a genome  {
            a: |
                - map to the genome
                - mark duplicates
                - base quality score calibration
                - generate aligment stats
                - convert a bam to a cram
            |
        }
        Trim sequence adapters -> Align reads to a genome: removal
        Somatic variant detection {
            mutect2 {
              a: |
              - collect pileup summaries
              - calculate cross-sample contamination
              - variant calling with mutect2
              - variant normalization
              - indel left alignment
              - functional annotation with VEP
              - convert a vcf to MAF format
              |
            }
            strelka2 {
              a: |
              - identify indel candidates by manta2
              - variant calling with strelka2
              - variant normalization
              - indel left alignment
              - functional annotation with VEP
              - convert a vcf to MAF format
              |
            }
          }
        Align reads to a genome ->  Somatic variant detection: discovery
        TMB estimation  {
          a: |
              - exclude germline and cosmic variants
              - synonymous and non-synonymous
              - inframe and frameshift indels
              - alternative allele count > 5
              - read depth > 250x
              |
      }
        Somatic variant detection -> TMB estimation: calibration
      }

      Sample Sheet -> Main workflow: Multiple sample processing