name: multiqc_report
description: Aggregate quality control metrics from Samtools, Picard, and FastQC for all samples
  in the cohort into a single report.
keywords:
  - Per-sample quality metrics
  - Mapping rates
  - Read duplication levels
  - Quantification summaries
tools:
  - multiqc:
      description: |
        MultiQC searches a given directory for analysis logs and compiles a HTML report.
        It's a general use tool, perfect for summarising the output from numerous bioinformatics tools.
      homepage: https://multiqc.info/
      documentation: https://multiqc.info/docs/
      licence: ["GPL-3.0-or-later"]
      identifier: biotools:multiqc
  - samtools:
      description: |
        SAMtools is a set of utilities for interacting with and post-processing
        short DNA sequence read alignments in the SAM, BAM and CRAM formats, written by Heng Li.
        These files are generated as output by short read aligners like BWA.
      homepage: http://www.htslib.org/
      documentation: http://www.htslib.org/doc/samtools.html
      doi: 10.1093/bioinformatics/btp352
      licence: ["MIT"]
  - picard:
      description: |
        A set of command line tools (in Java) for manipulating high-throughput sequencing (HTS)
        data and formats such as SAM/BAM/CRAM and VCF.
      homepage: https://broadinstitute.github.io/picard/
      documentation: https://broadinstitute.github.io/picard/
      licence: ["MIT"]
      identifier: biotools:picard_tools
  - fastqc:
      description: |
        FastQC gives general quality metrics about your reads.
        It provides information about the quality score distribution
        across your reads, the per base sequence content (%A/C/G/T).
        You get information about adapter contamination and other
        overrepresented sequences.
      homepage: https://www.bioinformatics.babraham.ac.uk/projects/fastqc/
      documentation: https://www.bioinformatics.babraham.ac.uk/projects/fastqc/Help/
      licence: ["GPL-2.0-only"]
input:
  - - qc_metrics_ch:
        type: file
        description: |
          Folders that store QC metrics generated by Samtools, Picard, and FastQC.
output:
  - report:
      - "*multiqc_report.html":
          type: file
          description: MultiQC HTML report
          pattern: "multiqc_report.html"
  - data:
      - "*_data":
          type: directory
          description: MultiQC data directory
          pattern: "multiqc_data"
  - versions:
      - versions.yml:
          type: file
          description: MULTIQC software application version
          pattern: "versions.yml"
authors:
  - "@kelseyz"
maintainers:
  - "@kelseyz"